### ISSUE TITLE
Add .gitattributes file

### ISSUE THREAD

**Issue by garak** [omines/akismet#4]
There are many files in this repository only useful for testing or other non-production purposes.
You should exclude them by adding a .gitattributes file.

**Comment by curry684** [comment]
What exactly would a gitattributes file achieve for this?

**Comment by garak** [comment]
It would exclude the aforementioned files from being part of the releases.
So, when someone installs this library, such files will not be present in their vendor folder.

**Comment by curry684** [comment]
Do you have an example of it being used for that?

**Comment by curry684** [comment]
Feel free to submit a PR if you really care about saving 9Kb.
