### ISSUE TITLE
Too strict type checking for Message type

### ISSUE THREAD

**Issue by karptonite** [omines/akismet#7]
In `AkismetMessage`, `setType` requires `$type` to be `MessageType`. However, Akismet allows you to send any string for a message type, as detailed [here](https://akismet.com/blog/pro-tip-tell-us-your-comment_type/).

For this reason, `setType()` should accept any string. We are running into this issue as we transition to this library because we use a custom message type in some cases.

Thanks for your work on this!

**Comment by curry684** [comment]
My apologies for the late response, missed this completely. We can fix this without B/C break by making the setters accept `MessageType|string` and converting it on the fly to store a string internally. We'd just need some magic in the getter to not break anything bad.

PR welcome or I'll pick it up later.

**Comment by curry684** [comment]
Implemented with full B/C.
